#!/usr/bin/env python3
"""Generate .pyi type stub files for the rusty_bacnet native extension.

Usage:
    1. Build the extension:  maturin develop
    2. Generate stubs:       python generate_stubs.py
    3. Stubs are written to: rusty_bacnet/__init__.pyi

This script introspects the compiled native module to produce accurate
type stubs, including all enum variants as class attributes.

Run this script whenever the Rust bindings change.
"""

from __future__ import annotations

import inspect
import textwrap
from pathlib import Path

# fmt: off
HEADER = '''\
"""Type stubs for rusty_bacnet - auto-generated by generate_stubs.py.

Do not edit manually. Regenerate with: python generate_stubs.py
"""

from typing import Any, AsyncIterator, Optional, Self

'''
# fmt: on

# ── Enum definitions ──────────────────────────────────────────────────────────
# Each entry: (ClassName, raw_type)
ENUM_CLASSES = [
    ("ObjectType", "int"),
    ("PropertyIdentifier", "int"),
    ("ErrorClass", "int"),
    ("ErrorCode", "int"),
    ("EnableDisable", "int"),
    ("ReinitializedState", "int"),
    ("Segmentation", "int"),
    ("LifeSafetyOperation", "int"),
    ("EventState", "int"),
    ("EventType", "int"),
    ("MessagePriority", "int"),
]


def generate_enum_stub(cls: type, name: str, raw_type: str) -> str:
    """Generate stub for a PyO3 enum-like class with class-level variants."""
    attrs = sorted(
        a for a in dir(cls)
        if not a.startswith("_") and a not in ("from_raw", "to_raw")
    )

    lines = [f"class {name}:"]
    # Class-level variant attributes
    for attr in attrs:
        lines.append(f"    {attr}: {name}")
    lines.append("")
    lines.append(f"    @staticmethod")
    lines.append(f"    def from_raw(value: {raw_type}) -> {name}: ...")
    lines.append(f"    def to_raw(self) -> {raw_type}: ...")
    lines.append(f"    def __repr__(self) -> str: ...")
    lines.append(f"    def __eq__(self, other: object) -> bool: ...")
    lines.append(f"    def __hash__(self) -> int: ...")
    lines.append("")
    return "\n".join(lines)


# ── Composite types ───────────────────────────────────────────────────────────

OBJECT_IDENTIFIER_STUB = """\
class ObjectIdentifier:
    def __init__(self, object_type: ObjectType, instance: int) -> None: ...
    @property
    def object_type(self) -> ObjectType: ...
    @property
    def instance(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
"""

PROPERTY_VALUE_STUB = """\
class PropertyValue:
    @staticmethod
    def null() -> PropertyValue: ...
    @staticmethod
    def boolean(value: bool) -> PropertyValue: ...
    @staticmethod
    def unsigned(value: int) -> PropertyValue: ...
    @staticmethod
    def signed(value: int) -> PropertyValue: ...
    @staticmethod
    def real(value: float) -> PropertyValue: ...
    @staticmethod
    def double(value: float) -> PropertyValue: ...
    @staticmethod
    def character_string(value: str) -> PropertyValue: ...
    @staticmethod
    def octet_string(value: bytes) -> PropertyValue: ...
    @staticmethod
    def enumerated(value: int) -> PropertyValue: ...
    @staticmethod
    def object_identifier(oid: ObjectIdentifier) -> PropertyValue: ...
    @property
    def tag(self) -> str: ...
    @property
    def value(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
"""

DISCOVERED_DEVICE_STUB = """\
class DiscoveredDevice:
    @property
    def object_identifier(self) -> ObjectIdentifier: ...
    @property
    def mac_address(self) -> list[int]: ...
    @property
    def max_apdu_length(self) -> int: ...
    @property
    def segmentation_supported(self) -> Segmentation: ...
    @property
    def vendor_id(self) -> int: ...
    @property
    def seconds_since_seen(self) -> float: ...
    def __repr__(self) -> str: ...
"""

COV_NOTIFICATION_STUB = """\
class CovNotification:
    @property
    def subscriber_process_identifier(self) -> int: ...
    @property
    def initiating_device_identifier(self) -> ObjectIdentifier: ...
    @property
    def monitored_object_identifier(self) -> ObjectIdentifier: ...
    @property
    def time_remaining(self) -> int: ...
    @property
    def values(self) -> list[dict[str, Any]]: ...
    def __repr__(self) -> str: ...
"""

COV_NOTIFICATION_ITERATOR_STUB = """\
class CovNotificationIterator:
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> CovNotification: ...
"""

# ── Exception types ───────────────────────────────────────────────────────────

EXCEPTION_STUBS = """\
class BacnetError(Exception): ...
class BacnetProtocolError(BacnetError): ...
class BacnetTimeoutError(BacnetError): ...
class BacnetRejectError(BacnetError): ...
class BacnetAbortError(BacnetError): ...
"""

# ── BACnetClient ──────────────────────────────────────────────────────────────

BACNET_CLIENT_STUB = """\
class BACnetClient:
    def __init__(
        self,
        interface: str = "0.0.0.0",
        port: int = 0xBAC0,
        broadcast_address: str = "255.255.255.255",
        apdu_timeout_ms: int = 6000,
        transport: str = "bip",
        sc_hub: Optional[str] = None,
        sc_vmac: Optional[bytes] = None,
        sc_ca_cert: Optional[str] = None,
        sc_client_cert: Optional[str] = None,
        sc_client_key: Optional[str] = None,
        sc_heartbeat_interval_ms: Optional[int] = None,
        sc_heartbeat_timeout_ms: Optional[int] = None,
        ipv6_interface: Optional[str] = None,
    ) -> None: ...

    async def __aenter__(self) -> BACnetClient: ...
    async def __aexit__(
        self,
        _exc_type: Optional[type] = None,
        _exc_val: Optional[BaseException] = None,
        _exc_tb: Optional[Any] = None,
    ) -> None: ...

    async def read_property(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
    ) -> PropertyValue: ...

    async def write_property(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        value: PropertyValue,
        priority: Optional[int] = None,
        array_index: Optional[int] = None,
    ) -> None: ...

    async def who_is(
        self,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def read_property_multiple(
        self,
        address: str,
        specs: list[tuple[ObjectIdentifier, list[tuple[PropertyIdentifier, Optional[int]]]]],
    ) -> list[dict[str, Any]]: ...

    async def write_property_multiple(
        self,
        address: str,
        specs: list[
            tuple[
                ObjectIdentifier,
                list[tuple[PropertyIdentifier, PropertyValue, Optional[int], Optional[int]]],
            ]
        ],
    ) -> None: ...

    async def subscribe_cov(
        self,
        address: str,
        subscriber_process_identifier: int,
        monitored_object_identifier: ObjectIdentifier,
        confirmed: bool,
        lifetime: Optional[int] = None,
    ) -> None: ...

    async def unsubscribe_cov(
        self,
        address: str,
        subscriber_process_identifier: int,
        monitored_object_identifier: ObjectIdentifier,
    ) -> None: ...

    async def cov_notifications(self) -> CovNotificationIterator: ...

    async def who_has_by_id(
        self,
        object_id: ObjectIdentifier,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def who_has_by_name(
        self,
        name: str,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def discovered_devices(self) -> list[DiscoveredDevice]: ...
    async def get_device(self, instance: int) -> Optional[DiscoveredDevice]: ...
    async def clear_devices(self) -> None: ...

    async def delete_object(
        self,
        address: str,
        object_id: ObjectIdentifier,
    ) -> None: ...

    async def create_object(
        self,
        address: str,
        object_specifier: dict[str, Any],
        initial_values: Optional[list[Any]] = None,
    ) -> ObjectIdentifier: ...

    async def device_communication_control(
        self,
        address: str,
        enable_disable: EnableDisable,
        time_duration: Optional[int] = None,
        password: Optional[str] = None,
    ) -> None: ...

    async def reinitialize_device(
        self,
        address: str,
        reinitialized_state: ReinitializedState,
        password: Optional[str] = None,
    ) -> None: ...

    async def acknowledge_alarm(
        self,
        address: str,
        acknowledging_process_identifier: int,
        event_object_identifier: ObjectIdentifier,
        event_state_acknowledged: EventState,
        acknowledgment_source: str,
    ) -> None: ...

    async def get_event_information(
        self,
        address: str,
        last_received_object_identifier: Optional[ObjectIdentifier] = None,
    ) -> list[dict[str, Any]]: ...

    async def read_range(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
        range_type: Optional[int] = None,
        reference_index: Optional[int] = None,
        reference_seq: Optional[int] = None,
        count: Optional[int] = None,
    ) -> dict[str, Any]: ...

    async def atomic_read_file(
        self,
        address: str,
        file_identifier: ObjectIdentifier,
        access_method: int,
        start_position: int = 0,
        requested_octet_count: int = 0,
        start_record: int = 0,
        requested_record_count: int = 0,
    ) -> dict[str, Any]: ...

    async def atomic_write_file(
        self,
        address: str,
        file_identifier: ObjectIdentifier,
        access_method: int,
        start_position: int = 0,
        file_data: bytes = b"",
        start_record: int = 0,
        record_count: int = 0,
        file_record_data: Optional[list[Any]] = None,
    ) -> None: ...

    async def add_list_element(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        list_of_elements: list[Any],
        array_index: Optional[int] = None,
    ) -> None: ...

    async def remove_list_element(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        list_of_elements: list[Any],
        array_index: Optional[int] = None,
    ) -> None: ...

    async def confirmed_private_transfer(
        self,
        address: str,
        vendor_id: int,
        service_number: int,
        service_parameters: Optional[bytes] = None,
    ) -> dict[str, Any]: ...

    async def unconfirmed_private_transfer(
        self,
        address: str,
        vendor_id: int,
        service_number: int,
        service_parameters: Optional[bytes] = None,
    ) -> None: ...

    async def confirmed_text_message(
        self,
        address: str,
        source_device: ObjectIdentifier,
        message_priority: MessagePriority,
        message: str,
        message_class_type: Optional[int] = None,
        message_class_value: Optional[int] = None,
    ) -> None: ...

    async def unconfirmed_text_message(
        self,
        address: str,
        source_device: ObjectIdentifier,
        message_priority: MessagePriority,
        message: str,
        message_class_type: Optional[int] = None,
        message_class_value: Optional[int] = None,
    ) -> None: ...

    async def life_safety_operation(
        self,
        address: str,
        requesting_process_identifier: int,
        requesting_source: str,
        operation: LifeSafetyOperation,
        object_identifier: Optional[ObjectIdentifier] = None,
    ) -> None: ...

    async def get_enrollment_summary(
        self,
        address: str,
        acknowledgment_filter: int = 0,
        event_state_filter: Optional[EventState] = None,
        event_type_filter: Optional[EventType] = None,
        min_priority: Optional[int] = None,
        max_priority: Optional[int] = None,
        notification_class_filter: Optional[int] = None,
    ) -> list[dict[str, Any]]: ...

    async def get_alarm_summary(self, address: str) -> list[dict[str, Any]]: ...

    async def subscribe_cov_property_multiple(
        self,
        address: str,
        subscriber_process_identifier: int,
        specs: list[Any],
        max_notification_delay: Optional[int] = None,
        issue_confirmed_notifications: Optional[bool] = None,
    ) -> None: ...

    async def who_am_i(self) -> dict[str, Any]: ...

    async def write_group(
        self,
        address: str,
        group_number: int,
        write_priority: int,
        change_list: list[Any],
        inhibit_delay: Optional[int] = None,
    ) -> None: ...

    async def vt_open(self, address: str, vt_class: int) -> dict[str, Any]: ...
    async def vt_close(self, address: str, session_ids: list[int]) -> None: ...

    async def vt_data(
        self,
        address: str,
        session_id: int,
        data: bytes,
        data_flag: int,
    ) -> bytes: ...

    async def confirmed_audit_notification(
        self,
        address: str,
        service_data: bytes,
    ) -> None: ...

    async def unconfirmed_audit_notification(
        self,
        address: str,
        service_data: bytes,
    ) -> None: ...

    async def audit_log_query(
        self,
        address: str,
        acknowledgment_filter: int,
        query_options_raw: list[int] = [],
    ) -> list[dict[str, Any]]: ...

    async def stop(self) -> None: ...
"""

# ── BACnetServer ──────────────────────────────────────────────────────────────

BACNET_SERVER_STUB = """\
class BACnetServer:
    def __init__(
        self,
        device_instance: int,
        device_name: str = "BACnet Device",
        interface: str = "0.0.0.0",
        port: int = 0xBAC0,
        broadcast_address: str = "255.255.255.255",
        transport: str = "bip",
        sc_hub: Optional[str] = None,
        sc_vmac: Optional[bytes] = None,
        sc_ca_cert: Optional[str] = None,
        sc_client_cert: Optional[str] = None,
        sc_client_key: Optional[str] = None,
        sc_heartbeat_interval_ms: Optional[int] = None,
        sc_heartbeat_timeout_ms: Optional[int] = None,
        ipv6_interface: Optional[str] = None,
    ) -> None: ...

    # Object creation methods (call before start)
    def add_analog_input(self, instance: int, name: str, units: int = 62, present_value: float = 0.0) -> None: ...
    def add_analog_output(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_analog_value(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_binary_input(self, instance: int, name: str) -> None: ...
    def add_binary_output(self, instance: int, name: str) -> None: ...
    def add_binary_value(self, instance: int, name: str) -> None: ...
    def add_multi_state_input(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_multi_state_output(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_multi_state_value(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_calendar(self, instance: int, name: str) -> None: ...
    def add_schedule(self, instance: int, name: str) -> None: ...
    def add_notification_class(self, instance: int, name: str, notification_class: int = 0) -> None: ...
    def add_trend_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_trend_log_multiple(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_event_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_loop(self, instance: int, name: str, output_units: int = 62) -> None: ...
    def add_audit_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_audit_reporter(self, instance: int, name: str) -> None: ...
    def add_command(self, instance: int, name: str) -> None: ...
    def add_timer(self, instance: int, name: str) -> None: ...
    def add_load_control(self, instance: int, name: str) -> None: ...
    def add_program(self, instance: int, name: str) -> None: ...
    def add_lighting_output(self, instance: int, name: str) -> None: ...
    def add_binary_lighting_output(self, instance: int, name: str) -> None: ...
    def add_life_safety_point(self, instance: int, name: str) -> None: ...
    def add_life_safety_zone(self, instance: int, name: str) -> None: ...
    def add_group(self, instance: int, name: str) -> None: ...
    def add_global_group(self, instance: int, name: str) -> None: ...
    def add_structured_view(self, instance: int, name: str) -> None: ...
    def add_notification_forwarder(self, instance: int, name: str) -> None: ...
    def add_alert_enrollment(self, instance: int, name: str) -> None: ...
    def add_access_door(self, instance: int, name: str) -> None: ...
    def add_access_credential(self, instance: int, name: str) -> None: ...
    def add_access_point(self, instance: int, name: str) -> None: ...
    def add_access_rights(self, instance: int, name: str) -> None: ...
    def add_access_user(self, instance: int, name: str) -> None: ...
    def add_access_zone(self, instance: int, name: str) -> None: ...
    def add_credential_data_input(self, instance: int, name: str) -> None: ...
    def add_elevator_group(self, instance: int, name: str) -> None: ...
    def add_escalator(self, instance: int, name: str) -> None: ...
    def add_averaging(self, instance: int, name: str) -> None: ...
    def add_integer_value(self, instance: int, name: str) -> None: ...
    def add_positive_integer_value(self, instance: int, name: str) -> None: ...
    def add_large_analog_value(self, instance: int, name: str) -> None: ...
    def add_character_string_value(self, instance: int, name: str) -> None: ...
    def add_octet_string_value(self, instance: int, name: str) -> None: ...
    def add_bit_string_value(self, instance: int, name: str) -> None: ...
    def add_date_value(self, instance: int, name: str) -> None: ...
    def add_time_value(self, instance: int, name: str) -> None: ...
    def add_date_time_value(self, instance: int, name: str) -> None: ...
    def add_date_pattern_value(self, instance: int, name: str) -> None: ...
    def add_time_pattern_value(self, instance: int, name: str) -> None: ...
    def add_date_time_pattern_value(self, instance: int, name: str) -> None: ...
    def add_accumulator(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_pulse_converter(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_file(self, instance: int, name: str, file_type: str = "application/octet-stream") -> None: ...
    def add_network_port(self, instance: int, name: str, network_type: int = 0) -> None: ...
    def add_event_enrollment(self, instance: int, name: str, event_type: int = 0) -> None: ...
    def add_channel(self, instance: int, name: str, channel_number: int) -> None: ...
    def add_staging(self, instance: int, name: str, num_stages: int) -> None: ...
    def add_lift(self, instance: int, name: str, num_floors: int) -> None: ...

    # Runtime methods (call after start)
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def local_address(self) -> str: ...
    async def read_property(
        self,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
    ) -> PropertyValue: ...
    async def write_property_local(
        self,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        value: PropertyValue,
        priority: Optional[int] = None,
        array_index: Optional[int] = None,
    ) -> None: ...
    async def comm_state(self) -> int: ...
"""

# ── ScHub ─────────────────────────────────────────────────────────────────────

SC_HUB_STUB = """\
class ScHub:
    def __init__(
        self,
        listen: str,
        cert: str,
        key: str,
        vmac: bytes,
        ca_cert: Optional[str] = None,
    ) -> None: ...

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def address(self) -> Optional[str]: ...
    async def url(self) -> Optional[str]: ...
"""


def generate_stubs() -> str:
    """Generate the complete .pyi stub content by introspecting the module."""
    import rusty_bacnet as rb

    parts: list[str] = [HEADER]

    # Exceptions
    parts.append(EXCEPTION_STUBS)

    # Enums (with runtime-introspected variants)
    for name, raw_type in ENUM_CLASSES:
        cls = getattr(rb, name)
        parts.append(generate_enum_stub(cls, name, raw_type))

    # Composite types
    parts.append(OBJECT_IDENTIFIER_STUB)
    parts.append(PROPERTY_VALUE_STUB)
    parts.append(DISCOVERED_DEVICE_STUB)
    parts.append(COV_NOTIFICATION_STUB)
    parts.append(COV_NOTIFICATION_ITERATOR_STUB)

    # Main classes
    parts.append(BACNET_CLIENT_STUB)
    parts.append(BACNET_SERVER_STUB)
    parts.append(SC_HUB_STUB)

    return "\n".join(parts)


def main() -> None:
    stub_content = generate_stubs()

    # Write to the package directory alongside __init__.py
    stub_dir = Path(__file__).parent / "rusty_bacnet"
    stub_dir.mkdir(exist_ok=True)

    stub_path = stub_dir / "__init__.pyi"
    stub_path.write_text(stub_content)
    print(f"Wrote stubs to {stub_path}")

    # Ensure py.typed marker exists
    py_typed = stub_dir / "py.typed"
    if not py_typed.exists():
        py_typed.write_text("")
        print(f"Created {py_typed}")


if __name__ == "__main__":
    main()
