"""Type stubs for rusty_bacnet - auto-generated by generate_stubs.py.

Do not edit manually. Regenerate with: python generate_stubs.py
"""

from typing import Any, AsyncIterator, Optional, Self


class BacnetError(Exception): ...
class BacnetProtocolError(BacnetError): ...
class BacnetTimeoutError(BacnetError): ...
class BacnetRejectError(BacnetError): ...
class BacnetAbortError(BacnetError): ...

class ObjectType:
    ACCESS_CREDENTIAL: ObjectType
    ACCESS_DOOR: ObjectType
    ACCESS_POINT: ObjectType
    ACCESS_RIGHTS: ObjectType
    ACCESS_USER: ObjectType
    ACCESS_ZONE: ObjectType
    ACCUMULATOR: ObjectType
    ALERT_ENROLLMENT: ObjectType
    ANALOG_INPUT: ObjectType
    ANALOG_OUTPUT: ObjectType
    ANALOG_VALUE: ObjectType
    AUDIT_LOG: ObjectType
    AUDIT_REPORTER: ObjectType
    AVERAGING: ObjectType
    BINARY_INPUT: ObjectType
    BINARY_LIGHTING_OUTPUT: ObjectType
    BINARY_OUTPUT: ObjectType
    BINARY_VALUE: ObjectType
    BITSTRING_VALUE: ObjectType
    CALENDAR: ObjectType
    CHANNEL: ObjectType
    CHARACTERSTRING_VALUE: ObjectType
    COMMAND: ObjectType
    CREDENTIAL_DATA_INPUT: ObjectType
    DATEPATTERN_VALUE: ObjectType
    DATETIMEPATTERN_VALUE: ObjectType
    DATETIME_VALUE: ObjectType
    DATE_VALUE: ObjectType
    DEVICE: ObjectType
    ELEVATOR_GROUP: ObjectType
    ESCALATOR: ObjectType
    EVENT_ENROLLMENT: ObjectType
    EVENT_LOG: ObjectType
    FILE: ObjectType
    GLOBAL_GROUP: ObjectType
    GROUP: ObjectType
    INTEGER_VALUE: ObjectType
    LARGE_ANALOG_VALUE: ObjectType
    LIFE_SAFETY_POINT: ObjectType
    LIFE_SAFETY_ZONE: ObjectType
    LIFT: ObjectType
    LIGHTING_OUTPUT: ObjectType
    LOAD_CONTROL: ObjectType
    LOOP: ObjectType
    MULTI_STATE_INPUT: ObjectType
    MULTI_STATE_OUTPUT: ObjectType
    MULTI_STATE_VALUE: ObjectType
    NETWORK_PORT: ObjectType
    NETWORK_SECURITY: ObjectType
    NOTIFICATION_CLASS: ObjectType
    NOTIFICATION_FORWARDER: ObjectType
    OCTETSTRING_VALUE: ObjectType
    POSITIVE_INTEGER_VALUE: ObjectType
    PROGRAM: ObjectType
    PULSE_CONVERTER: ObjectType
    SCHEDULE: ObjectType
    STAGING: ObjectType
    STRUCTURED_VIEW: ObjectType
    TIMEPATTERN_VALUE: ObjectType
    TIMER: ObjectType
    TIME_VALUE: ObjectType
    TREND_LOG: ObjectType
    TREND_LOG_MULTIPLE: ObjectType

    @staticmethod
    def from_raw(value: int) -> ObjectType: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PropertyIdentifier:
    ABSENTEE_LIMIT: PropertyIdentifier
    ACCEPTED_MODES: PropertyIdentifier
    ACCESS_ALARM_EVENTS: PropertyIdentifier
    ACCESS_DOORS: PropertyIdentifier
    ACCESS_EVENT: PropertyIdentifier
    ACCESS_EVENT_AUTHENTICATION_FACTOR: PropertyIdentifier
    ACCESS_EVENT_CREDENTIAL: PropertyIdentifier
    ACCESS_EVENT_TAG: PropertyIdentifier
    ACCESS_EVENT_TIME: PropertyIdentifier
    ACCESS_TRANSACTION_EVENTS: PropertyIdentifier
    ACCOMPANIMENT: PropertyIdentifier
    ACCOMPANIMENT_TIME: PropertyIdentifier
    ACKED_TRANSITIONS: PropertyIdentifier
    ACK_REQUIRED: PropertyIdentifier
    ACTION: PropertyIdentifier
    ACTION_TEXT: PropertyIdentifier
    ACTIVATION_TIME: PropertyIdentifier
    ACTIVE_AUTHENTICATION_POLICY: PropertyIdentifier
    ACTIVE_COV_MULTIPLE_SUBSCRIPTIONS: PropertyIdentifier
    ACTIVE_COV_SUBSCRIPTIONS: PropertyIdentifier
    ACTIVE_TEXT: PropertyIdentifier
    ACTIVE_VT_SESSIONS: PropertyIdentifier
    ACTUAL_SHED_LEVEL: PropertyIdentifier
    ADJUST_VALUE: PropertyIdentifier
    ALARM_VALUE: PropertyIdentifier
    ALARM_VALUES: PropertyIdentifier
    ALIGN_INTERVALS: PropertyIdentifier
    ALL: PropertyIdentifier
    ALLOW_GROUP_DELAY_INHIBIT: PropertyIdentifier
    ALL_WRITES_SUCCESSFUL: PropertyIdentifier
    APDU_LENGTH: PropertyIdentifier
    APDU_SEGMENT_TIMEOUT: PropertyIdentifier
    APDU_TIMEOUT: PropertyIdentifier
    APPLICATION_SOFTWARE_VERSION: PropertyIdentifier
    ARCHIVE: PropertyIdentifier
    ASSIGNED_ACCESS_RIGHTS: PropertyIdentifier
    ASSIGNED_LANDING_CALLS: PropertyIdentifier
    ATTEMPTED_SAMPLES: PropertyIdentifier
    AUDITABLE_OPERATIONS: PropertyIdentifier
    AUDIT_LEVEL: PropertyIdentifier
    AUDIT_NOTIFICATION_RECIPIENT: PropertyIdentifier
    AUDIT_PRIORITY_FILTER: PropertyIdentifier
    AUDIT_SOURCE_REPORTER: PropertyIdentifier
    AUTHENTICATION_FACTORS: PropertyIdentifier
    AUTHENTICATION_POLICY_LIST: PropertyIdentifier
    AUTHENTICATION_POLICY_NAMES: PropertyIdentifier
    AUTHENTICATION_STATUS: PropertyIdentifier
    AUTHORIZATION_EXEMPTIONS: PropertyIdentifier
    AUTHORIZATION_MODE: PropertyIdentifier
    AUTO_SLAVE_DISCOVERY: PropertyIdentifier
    AVERAGE_VALUE: PropertyIdentifier
    BACKUP_AND_RESTORE_STATE: PropertyIdentifier
    BACKUP_FAILURE_TIMEOUT: PropertyIdentifier
    BACKUP_PREPARATION_TIME: PropertyIdentifier
    BACNET_IPV6_MODE: PropertyIdentifier
    BACNET_IPV6_MULTICAST_ADDRESS: PropertyIdentifier
    BACNET_IPV6_UDP_PORT: PropertyIdentifier
    BACNET_IP_GLOBAL_ADDRESS: PropertyIdentifier
    BACNET_IP_MODE: PropertyIdentifier
    BACNET_IP_MULTICAST_ADDRESS: PropertyIdentifier
    BACNET_IP_NAT_TRAVERSAL: PropertyIdentifier
    BACNET_IP_UDP_PORT: PropertyIdentifier
    BASE_DEVICE_SECURITY_POLICY: PropertyIdentifier
    BBMD_ACCEPT_FD_REGISTRATIONS: PropertyIdentifier
    BBMD_BROADCAST_DISTRIBUTION_TABLE: PropertyIdentifier
    BBMD_FOREIGN_DEVICE_TABLE: PropertyIdentifier
    BELONGS_TO: PropertyIdentifier
    BIAS: PropertyIdentifier
    BIT_MASK: PropertyIdentifier
    BIT_TEXT: PropertyIdentifier
    BLINK_WARN_ENABLE: PropertyIdentifier
    BUFFER_SIZE: PropertyIdentifier
    CAR_ASSIGNED_DIRECTION: PropertyIdentifier
    CAR_DOOR_COMMAND: PropertyIdentifier
    CAR_DOOR_STATUS: PropertyIdentifier
    CAR_DOOR_TEXT: PropertyIdentifier
    CAR_DOOR_ZONE: PropertyIdentifier
    CAR_DRIVE_STATUS: PropertyIdentifier
    CAR_LOAD: PropertyIdentifier
    CAR_LOAD_UNITS: PropertyIdentifier
    CAR_MODE: PropertyIdentifier
    CAR_MOVING_DIRECTION: PropertyIdentifier
    CAR_POSITION: PropertyIdentifier
    CHANGES_PENDING: PropertyIdentifier
    CHANGE_OF_STATE_COUNT: PropertyIdentifier
    CHANGE_OF_STATE_TIME: PropertyIdentifier
    CHANNEL_NUMBER: PropertyIdentifier
    CLIENT_COV_INCREMENT: PropertyIdentifier
    COMMAND_NP: PropertyIdentifier
    COMMAND_TIME_ARRAY: PropertyIdentifier
    CONFIGURATION_FILES: PropertyIdentifier
    CONTROLLED_VARIABLE_REFERENCE: PropertyIdentifier
    CONTROLLED_VARIABLE_UNITS: PropertyIdentifier
    CONTROLLED_VARIABLE_VALUE: PropertyIdentifier
    CONTROL_GROUPS: PropertyIdentifier
    COUNT: PropertyIdentifier
    COUNT_BEFORE_CHANGE: PropertyIdentifier
    COUNT_CHANGE_TIME: PropertyIdentifier
    COVU_PERIOD: PropertyIdentifier
    COVU_RECIPIENTS: PropertyIdentifier
    COV_INCREMENT: PropertyIdentifier
    COV_PERIOD: PropertyIdentifier
    COV_RESUBSCRIPTION_INTERVAL: PropertyIdentifier
    CREDENTIALS: PropertyIdentifier
    CREDENTIALS_IN_ZONE: PropertyIdentifier
    CREDENTIAL_DISABLE: PropertyIdentifier
    CREDENTIAL_STATUS: PropertyIdentifier
    CURRENT_COMMAND_PRIORITY: PropertyIdentifier
    DATABASE_REVISION: PropertyIdentifier
    DATE_LIST: PropertyIdentifier
    DAYLIGHT_SAVINGS_STATUS: PropertyIdentifier
    DAYS_REMAINING: PropertyIdentifier
    DEADBAND: PropertyIdentifier
    DEFAULT_FADE_TIME: PropertyIdentifier
    DEFAULT_PRESENT_VALUE: PropertyIdentifier
    DEFAULT_RAMP_RATE: PropertyIdentifier
    DEFAULT_STEP_INCREMENT: PropertyIdentifier
    DEFAULT_SUBORDINATE_RELATIONSHIP: PropertyIdentifier
    DEFAULT_TIMEOUT: PropertyIdentifier
    DELETE_ON_FORWARD: PropertyIdentifier
    DEPLOYED_PROFILE_LOCATION: PropertyIdentifier
    DERIVATIVE_CONSTANT: PropertyIdentifier
    DERIVATIVE_CONSTANT_UNITS: PropertyIdentifier
    DESCRIPTION: PropertyIdentifier
    DESCRIPTION_OF_HALT: PropertyIdentifier
    DEVICE_ADDRESS_BINDING: PropertyIdentifier
    DEVICE_TYPE: PropertyIdentifier
    DEVICE_UUID: PropertyIdentifier
    DIRECT_READING: PropertyIdentifier
    DISTRIBUTION_KEY_REVISION: PropertyIdentifier
    DOOR_ALARM_STATE: PropertyIdentifier
    DOOR_EXTENDED_PULSE_TIME: PropertyIdentifier
    DOOR_MEMBERS: PropertyIdentifier
    DOOR_OPEN_TOO_LONG_TIME: PropertyIdentifier
    DOOR_PULSE_TIME: PropertyIdentifier
    DOOR_STATUS: PropertyIdentifier
    DOOR_UNLOCK_DELAY_TIME: PropertyIdentifier
    DO_NOT_HIDE: PropertyIdentifier
    DUTY_WINDOW: PropertyIdentifier
    EFFECTIVE_PERIOD: PropertyIdentifier
    EGRESS_ACTIVE: PropertyIdentifier
    EGRESS_TIME: PropertyIdentifier
    ELAPSED_ACTIVE_TIME: PropertyIdentifier
    ELEVATOR_GROUP: PropertyIdentifier
    ENERGY_METER: PropertyIdentifier
    ENERGY_METER_REF: PropertyIdentifier
    ENTRY_POINTS: PropertyIdentifier
    ERROR_LIMIT: PropertyIdentifier
    ESCALATOR_MODE: PropertyIdentifier
    EVENT_ALGORITHM_INHIBIT: PropertyIdentifier
    EVENT_ALGORITHM_INHIBIT_REF: PropertyIdentifier
    EVENT_DETECTION_ENABLE: PropertyIdentifier
    EVENT_ENABLE: PropertyIdentifier
    EVENT_MESSAGE_TEXTS: PropertyIdentifier
    EVENT_MESSAGE_TEXTS_CONFIG: PropertyIdentifier
    EVENT_PARAMETERS: PropertyIdentifier
    EVENT_STATE: PropertyIdentifier
    EVENT_TIME_STAMPS: PropertyIdentifier
    EVENT_TYPE: PropertyIdentifier
    EXCEPTION_SCHEDULE: PropertyIdentifier
    EXECUTION_DELAY: PropertyIdentifier
    EXIT_POINTS: PropertyIdentifier
    EXPECTED_SHED_LEVEL: PropertyIdentifier
    EXPIRATION_TIME: PropertyIdentifier
    EXTENDED_TIME_ENABLE: PropertyIdentifier
    FAILED_ATTEMPTS: PropertyIdentifier
    FAILED_ATTEMPTS_TIME: PropertyIdentifier
    FAILED_ATTEMPT_EVENTS: PropertyIdentifier
    FAULT_HIGH_LIMIT: PropertyIdentifier
    FAULT_LOW_LIMIT: PropertyIdentifier
    FAULT_PARAMETERS: PropertyIdentifier
    FAULT_SIGNALS: PropertyIdentifier
    FAULT_TYPE: PropertyIdentifier
    FAULT_VALUES: PropertyIdentifier
    FD_BBMD_ADDRESS: PropertyIdentifier
    FD_SUBSCRIPTION_LIFETIME: PropertyIdentifier
    FEEDBACK_VALUE: PropertyIdentifier
    FILE_ACCESS_METHOD: PropertyIdentifier
    FILE_SIZE: PropertyIdentifier
    FILE_TYPE: PropertyIdentifier
    FIRMWARE_REVISION: PropertyIdentifier
    FLOOR_NUMBER: PropertyIdentifier
    FLOOR_TEXT: PropertyIdentifier
    FULL_DUTY_BASELINE: PropertyIdentifier
    GLOBAL_IDENTIFIER: PropertyIdentifier
    GROUP_ID: PropertyIdentifier
    GROUP_MEMBERS: PropertyIdentifier
    GROUP_MEMBER_NAMES: PropertyIdentifier
    GROUP_MODE: PropertyIdentifier
    HIGHER_DECK: PropertyIdentifier
    HIGH_LIMIT: PropertyIdentifier
    INACTIVE_TEXT: PropertyIdentifier
    INITIAL_TIMEOUT: PropertyIdentifier
    INPUT_REFERENCE: PropertyIdentifier
    INSTALLATION_ID: PropertyIdentifier
    INSTANCE_OF: PropertyIdentifier
    INSTANTANEOUS_POWER: PropertyIdentifier
    INTEGRAL_CONSTANT: PropertyIdentifier
    INTEGRAL_CONSTANT_UNITS: PropertyIdentifier
    INTERFACE_VALUE: PropertyIdentifier
    INTERVAL_OFFSET: PropertyIdentifier
    IN_PROCESS: PropertyIdentifier
    IN_PROGRESS: PropertyIdentifier
    IPV6_ADDRESS: PropertyIdentifier
    IPV6_AUTO_ADDRESSING_ENABLE: PropertyIdentifier
    IPV6_DEFAULT_GATEWAY: PropertyIdentifier
    IPV6_DHCP_LEASE_TIME: PropertyIdentifier
    IPV6_DHCP_LEASE_TIME_REMAINING: PropertyIdentifier
    IPV6_DHCP_SERVER: PropertyIdentifier
    IPV6_DNS_SERVER: PropertyIdentifier
    IPV6_PREFIX_LENGTH: PropertyIdentifier
    IPV6_ZONE_INDEX: PropertyIdentifier
    IP_ADDRESS: PropertyIdentifier
    IP_DEFAULT_GATEWAY: PropertyIdentifier
    IP_DHCP_ENABLE: PropertyIdentifier
    IP_DHCP_LEASE_TIME: PropertyIdentifier
    IP_DHCP_LEASE_TIME_REMAINING: PropertyIdentifier
    IP_DHCP_SERVER: PropertyIdentifier
    IP_DNS_SERVER: PropertyIdentifier
    IP_SUBNET_MASK: PropertyIdentifier
    ISSUE_CONFIRMED_NOTIFICATIONS: PropertyIdentifier
    IS_UTC: PropertyIdentifier
    KEY_SETS: PropertyIdentifier
    LANDING_CALLS: PropertyIdentifier
    LANDING_CALL_CONTROL: PropertyIdentifier
    LANDING_DOOR_STATUS: PropertyIdentifier
    LAST_ACCESS_EVENT: PropertyIdentifier
    LAST_ACCESS_POINT: PropertyIdentifier
    LAST_COMMAND_TIME: PropertyIdentifier
    LAST_CREDENTIAL_ADDED: PropertyIdentifier
    LAST_CREDENTIAL_ADDED_TIME: PropertyIdentifier
    LAST_CREDENTIAL_REMOVED: PropertyIdentifier
    LAST_CREDENTIAL_REMOVED_TIME: PropertyIdentifier
    LAST_KEY_SERVER: PropertyIdentifier
    LAST_NOTIFY_RECORD: PropertyIdentifier
    LAST_PRIORITY: PropertyIdentifier
    LAST_RESTART_REASON: PropertyIdentifier
    LAST_RESTORE_TIME: PropertyIdentifier
    LAST_STATE_CHANGE: PropertyIdentifier
    LAST_USE_TIME: PropertyIdentifier
    LIFE_SAFETY_ALARM_VALUES: PropertyIdentifier
    LIGHTING_COMMAND: PropertyIdentifier
    LIGHTING_COMMAND_DEFAULT_PRIORITY: PropertyIdentifier
    LIMIT_ENABLE: PropertyIdentifier
    LIMIT_MONITORING_INTERVAL: PropertyIdentifier
    LINK_SPEED: PropertyIdentifier
    LINK_SPEEDS: PropertyIdentifier
    LINK_SPEED_AUTONEGOTIATE: PropertyIdentifier
    LIST_OF_GROUP_MEMBERS: PropertyIdentifier
    LIST_OF_OBJECT_PROPERTY_REFERENCES: PropertyIdentifier
    LOCAL_DATE: PropertyIdentifier
    LOCAL_FORWARDING_ONLY: PropertyIdentifier
    LOCAL_TIME: PropertyIdentifier
    LOCATION: PropertyIdentifier
    LOCKOUT: PropertyIdentifier
    LOCKOUT_RELINQUISH_TIME: PropertyIdentifier
    LOCK_STATUS: PropertyIdentifier
    LOGGING_OBJECT: PropertyIdentifier
    LOGGING_RECORD: PropertyIdentifier
    LOGGING_TYPE: PropertyIdentifier
    LOG_BUFFER: PropertyIdentifier
    LOG_DEVICE_OBJECT_PROPERTY: PropertyIdentifier
    LOG_ENABLE: PropertyIdentifier
    LOG_INTERVAL: PropertyIdentifier
    LOWER_DECK: PropertyIdentifier
    LOW_DIFF_LIMIT: PropertyIdentifier
    LOW_LIMIT: PropertyIdentifier
    MACHINE_ROOM_ID: PropertyIdentifier
    MAC_ADDRESS: PropertyIdentifier
    MAINTENANCE_REQUIRED: PropertyIdentifier
    MAKING_CAR_CALL: PropertyIdentifier
    MANIPULATED_VARIABLE_REFERENCE: PropertyIdentifier
    MANUAL_SLAVE_ADDRESS_BINDING: PropertyIdentifier
    MASKED_ALARM_VALUES: PropertyIdentifier
    MAXIMUM_OUTPUT: PropertyIdentifier
    MAXIMUM_SEND_DELAY: PropertyIdentifier
    MAXIMUM_VALUE: PropertyIdentifier
    MAXIMUM_VALUE_TIMESTAMP: PropertyIdentifier
    MAX_ACTUAL_VALUE: PropertyIdentifier
    MAX_APDU_LENGTH_ACCEPTED: PropertyIdentifier
    MAX_FAILED_ATTEMPTS: PropertyIdentifier
    MAX_INFO_FRAMES: PropertyIdentifier
    MAX_MASTER: PropertyIdentifier
    MAX_PRES_VALUE: PropertyIdentifier
    MAX_SEGMENTS_ACCEPTED: PropertyIdentifier
    MEMBERS: PropertyIdentifier
    MEMBER_OF: PropertyIdentifier
    MEMBER_STATUS_FLAGS: PropertyIdentifier
    MINIMUM_OFF_TIME: PropertyIdentifier
    MINIMUM_ON_TIME: PropertyIdentifier
    MINIMUM_OUTPUT: PropertyIdentifier
    MINIMUM_VALUE: PropertyIdentifier
    MINIMUM_VALUE_TIMESTAMP: PropertyIdentifier
    MIN_ACTUAL_VALUE: PropertyIdentifier
    MIN_PRES_VALUE: PropertyIdentifier
    MODE: PropertyIdentifier
    MODEL_NAME: PropertyIdentifier
    MODIFICATION_DATE: PropertyIdentifier
    MONITORED_OBJECTS: PropertyIdentifier
    MUSTER_POINT: PropertyIdentifier
    NEGATIVE_ACCESS_RULES: PropertyIdentifier
    NETWORK_ACCESS_SECURITY_POLICIES: PropertyIdentifier
    NETWORK_INTERFACE_NAME: PropertyIdentifier
    NETWORK_NUMBER: PropertyIdentifier
    NETWORK_NUMBER_QUALITY: PropertyIdentifier
    NETWORK_TYPE: PropertyIdentifier
    NEXT_STOPPING_FLOOR: PropertyIdentifier
    NODE_SUBTYPE: PropertyIdentifier
    NODE_TYPE: PropertyIdentifier
    NOTIFICATION_CLASS: PropertyIdentifier
    NOTIFICATION_THRESHOLD: PropertyIdentifier
    NOTIFY_TYPE: PropertyIdentifier
    NUMBER_OF_APDU_RETRIES: PropertyIdentifier
    NUMBER_OF_AUTHENTICATION_POLICIES: PropertyIdentifier
    NUMBER_OF_STATES: PropertyIdentifier
    OBJECT_IDENTIFIER: PropertyIdentifier
    OBJECT_LIST: PropertyIdentifier
    OBJECT_NAME: PropertyIdentifier
    OBJECT_PROPERTY_REFERENCE: PropertyIdentifier
    OBJECT_TYPE: PropertyIdentifier
    OCCUPANCY_COUNT: PropertyIdentifier
    OCCUPANCY_COUNT_ADJUST: PropertyIdentifier
    OCCUPANCY_COUNT_ENABLE: PropertyIdentifier
    OCCUPANCY_LOWER_LIMIT: PropertyIdentifier
    OCCUPANCY_LOWER_LIMIT_ENFORCED: PropertyIdentifier
    OCCUPANCY_STATE: PropertyIdentifier
    OCCUPANCY_UPPER_LIMIT: PropertyIdentifier
    OCCUPANCY_UPPER_LIMIT_ENFORCED: PropertyIdentifier
    OPERATION_DIRECTION: PropertyIdentifier
    OPERATION_EXPECTED: PropertyIdentifier
    OPTIONAL: PropertyIdentifier
    OUTPUT_UNITS: PropertyIdentifier
    OUT_OF_SERVICE: PropertyIdentifier
    PACKET_REORDER_TIME: PropertyIdentifier
    PASSBACK_MODE: PropertyIdentifier
    PASSBACK_TIMEOUT: PropertyIdentifier
    PASSENGER_ALARM: PropertyIdentifier
    POLARITY: PropertyIdentifier
    PORT_FILTER: PropertyIdentifier
    POSITIVE_ACCESS_RULES: PropertyIdentifier
    POWER: PropertyIdentifier
    POWER_MODE: PropertyIdentifier
    PRESCALE: PropertyIdentifier
    PRESENT_STAGE: PropertyIdentifier
    PRESENT_VALUE: PropertyIdentifier
    PRIORITY: PropertyIdentifier
    PRIORITY_ARRAY: PropertyIdentifier
    PRIORITY_FOR_WRITING: PropertyIdentifier
    PROCESS_IDENTIFIER: PropertyIdentifier
    PROCESS_IDENTIFIER_FILTER: PropertyIdentifier
    PROFILE_LOCATION: PropertyIdentifier
    PROFILE_NAME: PropertyIdentifier
    PROGRAM_CHANGE: PropertyIdentifier
    PROGRAM_LOCATION: PropertyIdentifier
    PROGRAM_STATE: PropertyIdentifier
    PROPERTY_LIST: PropertyIdentifier
    PROPORTIONAL_CONSTANT: PropertyIdentifier
    PROPORTIONAL_CONSTANT_UNITS: PropertyIdentifier
    PROTOCOL_LEVEL: PropertyIdentifier
    PROTOCOL_OBJECT_TYPES_SUPPORTED: PropertyIdentifier
    PROTOCOL_REVISION: PropertyIdentifier
    PROTOCOL_SERVICES_SUPPORTED: PropertyIdentifier
    PROTOCOL_VERSION: PropertyIdentifier
    PULSE_RATE: PropertyIdentifier
    READ_ONLY: PropertyIdentifier
    REASON_FOR_DISABLE: PropertyIdentifier
    REASON_FOR_HALT: PropertyIdentifier
    RECIPIENT_LIST: PropertyIdentifier
    RECORDS_SINCE_NOTIFICATION: PropertyIdentifier
    RECORD_COUNT: PropertyIdentifier
    REFERENCE_PORT: PropertyIdentifier
    REGISTERED_CAR_CALL: PropertyIdentifier
    RELIABILITY: PropertyIdentifier
    RELIABILITY_EVALUATION_INHIBIT: PropertyIdentifier
    RELINQUISH_DEFAULT: PropertyIdentifier
    REPRESENTS: PropertyIdentifier
    REQUESTED_SHED_LEVEL: PropertyIdentifier
    REQUESTED_UPDATE_INTERVAL: PropertyIdentifier
    REQUIRED: PropertyIdentifier
    RESOLUTION: PropertyIdentifier
    RESTART_NOTIFICATION_RECIPIENTS: PropertyIdentifier
    RESTORE_COMPLETION_TIME: PropertyIdentifier
    RESTORE_PREPARATION_TIME: PropertyIdentifier
    ROUTING_TABLE: PropertyIdentifier
    SCALE: PropertyIdentifier
    SCALE_FACTOR: PropertyIdentifier
    SCHEDULE_DEFAULT: PropertyIdentifier
    SECURED_STATUS: PropertyIdentifier
    SECURITY_PDU_TIMEOUT: PropertyIdentifier
    SECURITY_TIME_WINDOW: PropertyIdentifier
    SEGMENTATION_SUPPORTED: PropertyIdentifier
    SEND_NOW: PropertyIdentifier
    SERIAL_NUMBER: PropertyIdentifier
    SETPOINT: PropertyIdentifier
    SETPOINT_REFERENCE: PropertyIdentifier
    SETTING: PropertyIdentifier
    SHED_DURATION: PropertyIdentifier
    SHED_LEVELS: PropertyIdentifier
    SHED_LEVEL_DESCRIPTIONS: PropertyIdentifier
    SILENCED: PropertyIdentifier
    SLAVE_ADDRESS_BINDING: PropertyIdentifier
    SLAVE_PROXY_ENABLE: PropertyIdentifier
    STAGES: PropertyIdentifier
    STAGE_NAMES: PropertyIdentifier
    START_TIME: PropertyIdentifier
    STATE_CHANGE_VALUES: PropertyIdentifier
    STATE_DESCRIPTION: PropertyIdentifier
    STATE_TEXT: PropertyIdentifier
    STATUS_FLAGS: PropertyIdentifier
    STOP_TIME: PropertyIdentifier
    STOP_WHEN_FULL: PropertyIdentifier
    STRIKE_COUNT: PropertyIdentifier
    STRUCTURED_OBJECT_LIST: PropertyIdentifier
    SUBORDINATE_ANNOTATIONS: PropertyIdentifier
    SUBORDINATE_LIST: PropertyIdentifier
    SUBORDINATE_NODE_TYPES: PropertyIdentifier
    SUBORDINATE_RELATIONSHIPS: PropertyIdentifier
    SUBORDINATE_TAGS: PropertyIdentifier
    SUBSCRIBED_RECIPIENTS: PropertyIdentifier
    SUPPORTED_FORMATS: PropertyIdentifier
    SUPPORTED_FORMAT_CLASSES: PropertyIdentifier
    SUPPORTED_SECURITY_ALGORITHMS: PropertyIdentifier
    SYSTEM_STATUS: PropertyIdentifier
    TAGS: PropertyIdentifier
    TARGET_REFERENCES: PropertyIdentifier
    THREAT_AUTHORITY: PropertyIdentifier
    THREAT_LEVEL: PropertyIdentifier
    TIMER_RUNNING: PropertyIdentifier
    TIMER_STATE: PropertyIdentifier
    TIME_DELAY: PropertyIdentifier
    TIME_DELAY_NORMAL: PropertyIdentifier
    TIME_OF_ACTIVE_TIME_RESET: PropertyIdentifier
    TIME_OF_DEVICE_RESTART: PropertyIdentifier
    TIME_OF_STATE_COUNT_RESET: PropertyIdentifier
    TIME_OF_STRIKE_COUNT_RESET: PropertyIdentifier
    TIME_SYNCHRONIZATION_INTERVAL: PropertyIdentifier
    TIME_SYNCHRONIZATION_RECIPIENTS: PropertyIdentifier
    TOTAL_RECORD_COUNT: PropertyIdentifier
    TRACE_FLAG: PropertyIdentifier
    TRACKING_VALUE: PropertyIdentifier
    TRANSACTION_NOTIFICATION_CLASS: PropertyIdentifier
    TRANSITION: PropertyIdentifier
    TRIGGER: PropertyIdentifier
    UNITS: PropertyIdentifier
    UPDATE_INTERVAL: PropertyIdentifier
    UPDATE_KEY_SET_TIMEOUT: PropertyIdentifier
    UPDATE_TIME: PropertyIdentifier
    USER_EXTERNAL_IDENTIFIER: PropertyIdentifier
    USER_INFORMATION_REFERENCE: PropertyIdentifier
    USER_NAME: PropertyIdentifier
    USER_TYPE: PropertyIdentifier
    USES_REMAINING: PropertyIdentifier
    UTC_OFFSET: PropertyIdentifier
    UTC_TIME_SYNCHRONIZATION_RECIPIENTS: PropertyIdentifier
    VALID_SAMPLES: PropertyIdentifier
    VALUE_BEFORE_CHANGE: PropertyIdentifier
    VALUE_CHANGE_TIME: PropertyIdentifier
    VALUE_SET: PropertyIdentifier
    VALUE_SOURCE: PropertyIdentifier
    VALUE_SOURCE_ARRAY: PropertyIdentifier
    VARIANCE_VALUE: PropertyIdentifier
    VENDOR_IDENTIFIER: PropertyIdentifier
    VENDOR_NAME: PropertyIdentifier
    VERIFICATION_TIME: PropertyIdentifier
    VIRTUAL_MAC_ADDRESS_TABLE: PropertyIdentifier
    VT_CLASSES_SUPPORTED: PropertyIdentifier
    WEEKLY_SCHEDULE: PropertyIdentifier
    WINDOW_INTERVAL: PropertyIdentifier
    WINDOW_SAMPLES: PropertyIdentifier
    WRITE_STATUS: PropertyIdentifier
    ZONE_FROM: PropertyIdentifier
    ZONE_MEMBERS: PropertyIdentifier
    ZONE_TO: PropertyIdentifier

    @staticmethod
    def from_raw(value: int) -> PropertyIdentifier: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ErrorClass:
    COMMUNICATION: ErrorClass
    DEVICE: ErrorClass
    OBJECT: ErrorClass
    PROPERTY: ErrorClass
    RESOURCES: ErrorClass
    SECURITY: ErrorClass
    SERVICES: ErrorClass
    VT: ErrorClass

    @staticmethod
    def from_raw(value: int) -> ErrorClass: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ErrorCode:
    ABORT_APDU_TOO_LONG: ErrorCode
    ABORT_APPLICATION_EXCEEDED_REPLY_TIME: ErrorCode
    ABORT_BUFFER_OVERFLOW: ErrorCode
    ABORT_INSUFFICIENT_SECURITY: ErrorCode
    ABORT_INVALID_APDU_IN_THIS_STATE: ErrorCode
    ABORT_OTHER: ErrorCode
    ABORT_OUT_OF_RESOURCES: ErrorCode
    ABORT_PREEMPTED_BY_HIGHER_PRIORITY_TASK: ErrorCode
    ABORT_PROPRIETARY: ErrorCode
    ABORT_SECURITY_ERROR: ErrorCode
    ABORT_SEGMENTATION_NOT_SUPPORTED: ErrorCode
    ABORT_TSM_TIMEOUT: ErrorCode
    ABORT_WINDOW_SIZE_OUT_OF_RANGE: ErrorCode
    ACCESS_DENIED: ErrorCode
    ADDRESSING_ERROR: ErrorCode
    AUTHENTICATION_FAILED: ErrorCode
    BAD_DESTINATION_ADDRESS: ErrorCode
    BAD_DESTINATION_DEVICE_ID: ErrorCode
    BAD_SIGNATURE: ErrorCode
    BAD_SOURCE_ADDRESS: ErrorCode
    BAD_TIMESTAMP: ErrorCode
    BUSY: ErrorCode
    CANNOT_USE_KEY: ErrorCode
    CANNOT_VERIFY_MESSAGE_ID: ErrorCode
    CHARACTER_SET_NOT_SUPPORTED: ErrorCode
    COMMUNICATION_DISABLED: ErrorCode
    CONFIGURATION_IN_PROGRESS: ErrorCode
    CORRECT_KEY_REVISION: ErrorCode
    COV_SUBSCRIPTION_FAILED: ErrorCode
    DATATYPE_NOT_SUPPORTED: ErrorCode
    DELETE_FDT_ENTRY_FAILED: ErrorCode
    DESTINATION_DEVICE_ID_REQUIRED: ErrorCode
    DEVICE_BUSY: ErrorCode
    DISTRIBUTE_BROADCAST_FAILED: ErrorCode
    DUPLICATE_ENTRY: ErrorCode
    DUPLICATE_MESSAGE: ErrorCode
    DUPLICATE_NAME: ErrorCode
    DUPLICATE_OBJECT_ID: ErrorCode
    DYNAMIC_CREATION_NOT_SUPPORTED: ErrorCode
    ENCRYPTION_NOT_CONFIGURED: ErrorCode
    ENCRYPTION_REQUIRED: ErrorCode
    FILE_ACCESS_DENIED: ErrorCode
    FILE_FULL: ErrorCode
    INCOMPATIBLE_SECURITY_LEVELS: ErrorCode
    INCONSISTENT_CONFIGURATION: ErrorCode
    INCONSISTENT_OBJECT_TYPE: ErrorCode
    INCONSISTENT_PARAMETERS: ErrorCode
    INCONSISTENT_SELECTION_CRITERION: ErrorCode
    INCORRECT_KEY: ErrorCode
    INTERNAL_ERROR: ErrorCode
    INVALID_ARRAY_INDEX: ErrorCode
    INVALID_CONFIGURATION_DATA: ErrorCode
    INVALID_DATA_TYPE: ErrorCode
    INVALID_EVENT_STATE: ErrorCode
    INVALID_FILE_ACCESS_METHOD: ErrorCode
    INVALID_FILE_START_POSITION: ErrorCode
    INVALID_KEY_DATA: ErrorCode
    INVALID_OPERATOR_NAME: ErrorCode
    INVALID_PARAMETER_DATA_TYPE: ErrorCode
    INVALID_TAG: ErrorCode
    INVALID_TIME_STAMP: ErrorCode
    INVALID_VALUE_IN_THIS_STATE: ErrorCode
    KEY_GENERATION_ERROR: ErrorCode
    KEY_UPDATE_IN_PROGRESS: ErrorCode
    LIST_ELEMENT_NOT_FOUND: ErrorCode
    LOGGED_VALUE_PURGED: ErrorCode
    LOG_BUFFER_FULL: ErrorCode
    MALFORMED_MESSAGE: ErrorCode
    MESSAGE_TOO_LONG: ErrorCode
    MISSING_REQUIRED_PARAMETER: ErrorCode
    NETWORK_DOWN: ErrorCode
    NOT_CONFIGURED: ErrorCode
    NOT_CONFIGURED_FOR_TRIGGERED_LOGGING: ErrorCode
    NOT_COV_PROPERTY: ErrorCode
    NOT_KEY_SERVER: ErrorCode
    NOT_ROUTER_TO_DNET: ErrorCode
    NO_ALARM_CONFIGURED: ErrorCode
    NO_OBJECTS_OF_SPECIFIED_TYPE: ErrorCode
    NO_PROPERTY_SPECIFIED: ErrorCode
    NO_SPACE_FOR_OBJECT: ErrorCode
    NO_SPACE_TO_ADD_LIST_ELEMENT: ErrorCode
    NO_SPACE_TO_WRITE_PROPERTY: ErrorCode
    NO_VT_SESSIONS_AVAILABLE: ErrorCode
    OBJECT_DELETION_NOT_PERMITTED: ErrorCode
    OBJECT_IDENTIFIER_ALREADY_EXISTS: ErrorCode
    OPERATIONAL_PROBLEM: ErrorCode
    OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED: ErrorCode
    OTHER: ErrorCode
    OUT_OF_MEMORY: ErrorCode
    PARAMETER_OUT_OF_RANGE: ErrorCode
    PASSWORD_FAILURE: ErrorCode
    PROPERTY_IS_NOT_AN_ARRAY: ErrorCode
    PROPERTY_IS_NOT_A_LIST: ErrorCode
    READ_ACCESS_DENIED: ErrorCode
    READ_BDT_FAILED: ErrorCode
    READ_FDT_FAILED: ErrorCode
    REGISTER_FOREIGN_DEVICE_FAILED: ErrorCode
    REJECT_BUFFER_OVERFLOW: ErrorCode
    REJECT_INCONSISTENT_PARAMETERS: ErrorCode
    REJECT_INVALID_PARAMETER_DATA_TYPE: ErrorCode
    REJECT_INVALID_TAG: ErrorCode
    REJECT_MISSING_REQUIRED_PARAMETER: ErrorCode
    REJECT_OTHER: ErrorCode
    REJECT_PARAMETER_OUT_OF_RANGE: ErrorCode
    REJECT_PROPRIETARY: ErrorCode
    REJECT_TOO_MANY_ARGUMENTS: ErrorCode
    REJECT_UNDEFINED_ENUMERATION: ErrorCode
    REJECT_UNRECOGNIZED_SERVICE: ErrorCode
    ROUTER_BUSY: ErrorCode
    SECURITY_ERROR: ErrorCode
    SECURITY_NOT_CONFIGURED: ErrorCode
    SECURITY_NOT_SUPPORTED: ErrorCode
    SERVICE_REQUEST_DENIED: ErrorCode
    SOURCE_SECURITY_REQUIRED: ErrorCode
    SUCCESS: ErrorCode
    TIMEOUT: ErrorCode
    TOO_MANY_KEYS: ErrorCode
    UNKNOWN_AUTHENTICATION_TYPE: ErrorCode
    UNKNOWN_DEVICE: ErrorCode
    UNKNOWN_FILE_SIZE: ErrorCode
    UNKNOWN_KEY: ErrorCode
    UNKNOWN_KEY_REVISION: ErrorCode
    UNKNOWN_NETWORK_MESSAGE: ErrorCode
    UNKNOWN_OBJECT: ErrorCode
    UNKNOWN_PROPERTY: ErrorCode
    UNKNOWN_ROUTE: ErrorCode
    UNKNOWN_SOURCE_MESSAGE: ErrorCode
    UNKNOWN_SUBSCRIPTION: ErrorCode
    UNKNOWN_VT_CLASS: ErrorCode
    UNKNOWN_VT_SESSION: ErrorCode
    UNSUPPORTED_OBJECT_TYPE: ErrorCode
    VALUE_NOT_INITIALIZED: ErrorCode
    VALUE_OUT_OF_RANGE: ErrorCode
    VALUE_TOO_LONG: ErrorCode
    VT_SESSION_ALREADY_CLOSED: ErrorCode
    VT_SESSION_TERMINATION_FAILURE: ErrorCode
    WRITE_ACCESS_DENIED: ErrorCode
    WRITE_BDT_FAILED: ErrorCode

    @staticmethod
    def from_raw(value: int) -> ErrorCode: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EnableDisable:
    DISABLE: EnableDisable
    DISABLE_INITIATION: EnableDisable
    ENABLE: EnableDisable

    @staticmethod
    def from_raw(value: int) -> EnableDisable: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ReinitializedState:
    ABORT_RESTORE: ReinitializedState
    ACTIVATE_CHANGES: ReinitializedState
    COLDSTART: ReinitializedState
    END_BACKUP: ReinitializedState
    END_RESTORE: ReinitializedState
    START_BACKUP: ReinitializedState
    START_RESTORE: ReinitializedState
    WARMSTART: ReinitializedState

    @staticmethod
    def from_raw(value: int) -> ReinitializedState: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Segmentation:
    BOTH: Segmentation
    NONE: Segmentation
    RECEIVE: Segmentation
    TRANSMIT: Segmentation

    @staticmethod
    def from_raw(value: int) -> Segmentation: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class LifeSafetyOperation:
    NONE: LifeSafetyOperation
    RESET: LifeSafetyOperation
    RESET_ALARM: LifeSafetyOperation
    RESET_FAULT: LifeSafetyOperation
    SILENCE: LifeSafetyOperation
    SILENCE_ALL: LifeSafetyOperation
    SILENCE_AUDIBLE: LifeSafetyOperation
    SILENCE_VISUAL: LifeSafetyOperation
    UNSILENCE: LifeSafetyOperation
    UNSILENCE_ALL: LifeSafetyOperation
    UNSILENCE_AUDIBLE: LifeSafetyOperation
    UNSILENCE_VISUAL: LifeSafetyOperation

    @staticmethod
    def from_raw(value: int) -> LifeSafetyOperation: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EventState:
    FAULT: EventState
    HIGH_LIMIT: EventState
    LIFE_SAFETY_ALARM: EventState
    LOW_LIMIT: EventState
    NORMAL: EventState
    OFFNORMAL: EventState

    @staticmethod
    def from_raw(value: int) -> EventState: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EventType:
    ACCESS_EVENT: EventType
    BUFFER_READY: EventType
    CHANGE_OF_BITSTRING: EventType
    CHANGE_OF_CHARACTERSTRING: EventType
    CHANGE_OF_DISCRETE_VALUE: EventType
    CHANGE_OF_LIFE_SAFETY: EventType
    CHANGE_OF_RELIABILITY: EventType
    CHANGE_OF_STATE: EventType
    CHANGE_OF_STATUS_FLAGS: EventType
    CHANGE_OF_TIMER: EventType
    CHANGE_OF_VALUE: EventType
    COMMAND_FAILURE: EventType
    DOUBLE_OUT_OF_RANGE: EventType
    EXTENDED: EventType
    FLOATING_LIMIT: EventType
    NONE: EventType
    OUT_OF_RANGE: EventType
    SIGNED_OUT_OF_RANGE: EventType
    UNSIGNED_OUT_OF_RANGE: EventType
    UNSIGNED_RANGE: EventType

    @staticmethod
    def from_raw(value: int) -> EventType: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class MessagePriority:
    NORMAL: MessagePriority
    URGENT: MessagePriority

    @staticmethod
    def from_raw(value: int) -> MessagePriority: ...
    def to_raw(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ObjectIdentifier:
    def __init__(self, object_type: ObjectType, instance: int) -> None: ...
    @property
    def object_type(self) -> ObjectType: ...
    @property
    def instance(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PropertyValue:
    @staticmethod
    def null() -> PropertyValue: ...
    @staticmethod
    def boolean(value: bool) -> PropertyValue: ...
    @staticmethod
    def unsigned(value: int) -> PropertyValue: ...
    @staticmethod
    def signed(value: int) -> PropertyValue: ...
    @staticmethod
    def real(value: float) -> PropertyValue: ...
    @staticmethod
    def double(value: float) -> PropertyValue: ...
    @staticmethod
    def character_string(value: str) -> PropertyValue: ...
    @staticmethod
    def octet_string(value: bytes) -> PropertyValue: ...
    @staticmethod
    def enumerated(value: int) -> PropertyValue: ...
    @staticmethod
    def object_identifier(oid: ObjectIdentifier) -> PropertyValue: ...
    @property
    def tag(self) -> str: ...
    @property
    def value(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DiscoveredDevice:
    @property
    def object_identifier(self) -> ObjectIdentifier: ...
    @property
    def mac_address(self) -> list[int]: ...
    @property
    def max_apdu_length(self) -> int: ...
    @property
    def segmentation_supported(self) -> Segmentation: ...
    @property
    def vendor_id(self) -> int: ...
    @property
    def seconds_since_seen(self) -> float: ...
    def __repr__(self) -> str: ...

class CovNotification:
    @property
    def subscriber_process_identifier(self) -> int: ...
    @property
    def initiating_device_identifier(self) -> ObjectIdentifier: ...
    @property
    def monitored_object_identifier(self) -> ObjectIdentifier: ...
    @property
    def time_remaining(self) -> int: ...
    @property
    def values(self) -> list[dict[str, Any]]: ...
    def __repr__(self) -> str: ...

class CovNotificationIterator:
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> CovNotification: ...

class BACnetClient:
    def __init__(
        self,
        interface: str = "0.0.0.0",
        port: int = 0xBAC0,
        broadcast_address: str = "255.255.255.255",
        apdu_timeout_ms: int = 6000,
        transport: str = "bip",
        sc_hub: Optional[str] = None,
        sc_vmac: Optional[bytes] = None,
        sc_ca_cert: Optional[str] = None,
        sc_client_cert: Optional[str] = None,
        sc_client_key: Optional[str] = None,
        sc_heartbeat_interval_ms: Optional[int] = None,
        sc_heartbeat_timeout_ms: Optional[int] = None,
        ipv6_interface: Optional[str] = None,
    ) -> None: ...

    async def __aenter__(self) -> BACnetClient: ...
    async def __aexit__(
        self,
        _exc_type: Optional[type] = None,
        _exc_val: Optional[BaseException] = None,
        _exc_tb: Optional[Any] = None,
    ) -> None: ...

    async def read_property(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
    ) -> PropertyValue: ...

    async def write_property(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        value: PropertyValue,
        priority: Optional[int] = None,
        array_index: Optional[int] = None,
    ) -> None: ...

    async def who_is(
        self,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def read_property_multiple(
        self,
        address: str,
        specs: list[tuple[ObjectIdentifier, list[tuple[PropertyIdentifier, Optional[int]]]]],
    ) -> list[dict[str, Any]]: ...

    async def write_property_multiple(
        self,
        address: str,
        specs: list[
            tuple[
                ObjectIdentifier,
                list[tuple[PropertyIdentifier, PropertyValue, Optional[int], Optional[int]]],
            ]
        ],
    ) -> None: ...

    async def subscribe_cov(
        self,
        address: str,
        subscriber_process_identifier: int,
        monitored_object_identifier: ObjectIdentifier,
        confirmed: bool,
        lifetime: Optional[int] = None,
    ) -> None: ...

    async def unsubscribe_cov(
        self,
        address: str,
        subscriber_process_identifier: int,
        monitored_object_identifier: ObjectIdentifier,
    ) -> None: ...

    async def cov_notifications(self) -> CovNotificationIterator: ...

    async def who_has_by_id(
        self,
        object_id: ObjectIdentifier,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def who_has_by_name(
        self,
        name: str,
        low_limit: Optional[int] = None,
        high_limit: Optional[int] = None,
    ) -> list[DiscoveredDevice]: ...

    async def discovered_devices(self) -> list[DiscoveredDevice]: ...
    async def get_device(self, instance: int) -> Optional[DiscoveredDevice]: ...
    async def clear_devices(self) -> None: ...

    async def delete_object(
        self,
        address: str,
        object_id: ObjectIdentifier,
    ) -> None: ...

    async def create_object(
        self,
        address: str,
        object_specifier: dict[str, Any],
        initial_values: Optional[list[Any]] = None,
    ) -> ObjectIdentifier: ...

    async def device_communication_control(
        self,
        address: str,
        enable_disable: EnableDisable,
        time_duration: Optional[int] = None,
        password: Optional[str] = None,
    ) -> None: ...

    async def reinitialize_device(
        self,
        address: str,
        reinitialized_state: ReinitializedState,
        password: Optional[str] = None,
    ) -> None: ...

    async def acknowledge_alarm(
        self,
        address: str,
        acknowledging_process_identifier: int,
        event_object_identifier: ObjectIdentifier,
        event_state_acknowledged: EventState,
        acknowledgment_source: str,
    ) -> None: ...

    async def get_event_information(
        self,
        address: str,
        last_received_object_identifier: Optional[ObjectIdentifier] = None,
    ) -> list[dict[str, Any]]: ...

    async def read_range(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
        range_type: Optional[int] = None,
        reference_index: Optional[int] = None,
        reference_seq: Optional[int] = None,
        count: Optional[int] = None,
    ) -> dict[str, Any]: ...

    async def atomic_read_file(
        self,
        address: str,
        file_identifier: ObjectIdentifier,
        access_method: int,
        start_position: int = 0,
        requested_octet_count: int = 0,
        start_record: int = 0,
        requested_record_count: int = 0,
    ) -> dict[str, Any]: ...

    async def atomic_write_file(
        self,
        address: str,
        file_identifier: ObjectIdentifier,
        access_method: int,
        start_position: int = 0,
        file_data: bytes = b"",
        start_record: int = 0,
        record_count: int = 0,
        file_record_data: Optional[list[Any]] = None,
    ) -> None: ...

    async def add_list_element(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        list_of_elements: list[Any],
        array_index: Optional[int] = None,
    ) -> None: ...

    async def remove_list_element(
        self,
        address: str,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        list_of_elements: list[Any],
        array_index: Optional[int] = None,
    ) -> None: ...

    async def confirmed_private_transfer(
        self,
        address: str,
        vendor_id: int,
        service_number: int,
        service_parameters: Optional[bytes] = None,
    ) -> dict[str, Any]: ...

    async def unconfirmed_private_transfer(
        self,
        address: str,
        vendor_id: int,
        service_number: int,
        service_parameters: Optional[bytes] = None,
    ) -> None: ...

    async def confirmed_text_message(
        self,
        address: str,
        source_device: ObjectIdentifier,
        message_priority: MessagePriority,
        message: str,
        message_class_type: Optional[int] = None,
        message_class_value: Optional[int] = None,
    ) -> None: ...

    async def unconfirmed_text_message(
        self,
        address: str,
        source_device: ObjectIdentifier,
        message_priority: MessagePriority,
        message: str,
        message_class_type: Optional[int] = None,
        message_class_value: Optional[int] = None,
    ) -> None: ...

    async def life_safety_operation(
        self,
        address: str,
        requesting_process_identifier: int,
        requesting_source: str,
        operation: LifeSafetyOperation,
        object_identifier: Optional[ObjectIdentifier] = None,
    ) -> None: ...

    async def get_enrollment_summary(
        self,
        address: str,
        acknowledgment_filter: int = 0,
        event_state_filter: Optional[EventState] = None,
        event_type_filter: Optional[EventType] = None,
        min_priority: Optional[int] = None,
        max_priority: Optional[int] = None,
        notification_class_filter: Optional[int] = None,
    ) -> list[dict[str, Any]]: ...

    async def get_alarm_summary(self, address: str) -> list[dict[str, Any]]: ...

    async def subscribe_cov_property_multiple(
        self,
        address: str,
        subscriber_process_identifier: int,
        specs: list[Any],
        max_notification_delay: Optional[int] = None,
        issue_confirmed_notifications: Optional[bool] = None,
    ) -> None: ...

    async def who_am_i(self) -> dict[str, Any]: ...

    async def write_group(
        self,
        address: str,
        group_number: int,
        write_priority: int,
        change_list: list[Any],
        inhibit_delay: Optional[int] = None,
    ) -> None: ...

    async def vt_open(self, address: str, vt_class: int) -> dict[str, Any]: ...
    async def vt_close(self, address: str, session_ids: list[int]) -> None: ...

    async def vt_data(
        self,
        address: str,
        session_id: int,
        data: bytes,
        data_flag: int,
    ) -> bytes: ...

    async def confirmed_audit_notification(
        self,
        address: str,
        service_data: bytes,
    ) -> None: ...

    async def unconfirmed_audit_notification(
        self,
        address: str,
        service_data: bytes,
    ) -> None: ...

    async def audit_log_query(
        self,
        address: str,
        acknowledgment_filter: int,
        query_options_raw: list[int] = [],
    ) -> list[dict[str, Any]]: ...

    async def stop(self) -> None: ...

class BACnetServer:
    def __init__(
        self,
        device_instance: int,
        device_name: str = "BACnet Device",
        interface: str = "0.0.0.0",
        port: int = 0xBAC0,
        broadcast_address: str = "255.255.255.255",
        transport: str = "bip",
        sc_hub: Optional[str] = None,
        sc_vmac: Optional[bytes] = None,
        sc_ca_cert: Optional[str] = None,
        sc_client_cert: Optional[str] = None,
        sc_client_key: Optional[str] = None,
        sc_heartbeat_interval_ms: Optional[int] = None,
        sc_heartbeat_timeout_ms: Optional[int] = None,
        ipv6_interface: Optional[str] = None,
    ) -> None: ...

    # Object creation methods (call before start)
    def add_analog_input(self, instance: int, name: str, units: int = 62, present_value: float = 0.0) -> None: ...
    def add_analog_output(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_analog_value(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_binary_input(self, instance: int, name: str) -> None: ...
    def add_binary_output(self, instance: int, name: str) -> None: ...
    def add_binary_value(self, instance: int, name: str) -> None: ...
    def add_multi_state_input(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_multi_state_output(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_multi_state_value(self, instance: int, name: str, number_of_states: int) -> None: ...
    def add_calendar(self, instance: int, name: str) -> None: ...
    def add_schedule(self, instance: int, name: str) -> None: ...
    def add_notification_class(self, instance: int, name: str, notification_class: int = 0) -> None: ...
    def add_trend_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_trend_log_multiple(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_event_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_loop(self, instance: int, name: str, output_units: int = 62) -> None: ...
    def add_audit_log(self, instance: int, name: str, buffer_size: int = 100) -> None: ...
    def add_audit_reporter(self, instance: int, name: str) -> None: ...
    def add_command(self, instance: int, name: str) -> None: ...
    def add_timer(self, instance: int, name: str) -> None: ...
    def add_load_control(self, instance: int, name: str) -> None: ...
    def add_program(self, instance: int, name: str) -> None: ...
    def add_lighting_output(self, instance: int, name: str) -> None: ...
    def add_binary_lighting_output(self, instance: int, name: str) -> None: ...
    def add_life_safety_point(self, instance: int, name: str) -> None: ...
    def add_life_safety_zone(self, instance: int, name: str) -> None: ...
    def add_group(self, instance: int, name: str) -> None: ...
    def add_global_group(self, instance: int, name: str) -> None: ...
    def add_structured_view(self, instance: int, name: str) -> None: ...
    def add_notification_forwarder(self, instance: int, name: str) -> None: ...
    def add_alert_enrollment(self, instance: int, name: str) -> None: ...
    def add_access_door(self, instance: int, name: str) -> None: ...
    def add_access_credential(self, instance: int, name: str) -> None: ...
    def add_access_point(self, instance: int, name: str) -> None: ...
    def add_access_rights(self, instance: int, name: str) -> None: ...
    def add_access_user(self, instance: int, name: str) -> None: ...
    def add_access_zone(self, instance: int, name: str) -> None: ...
    def add_credential_data_input(self, instance: int, name: str) -> None: ...
    def add_elevator_group(self, instance: int, name: str) -> None: ...
    def add_escalator(self, instance: int, name: str) -> None: ...
    def add_averaging(self, instance: int, name: str) -> None: ...
    def add_integer_value(self, instance: int, name: str) -> None: ...
    def add_positive_integer_value(self, instance: int, name: str) -> None: ...
    def add_large_analog_value(self, instance: int, name: str) -> None: ...
    def add_character_string_value(self, instance: int, name: str) -> None: ...
    def add_octet_string_value(self, instance: int, name: str) -> None: ...
    def add_bit_string_value(self, instance: int, name: str) -> None: ...
    def add_date_value(self, instance: int, name: str) -> None: ...
    def add_time_value(self, instance: int, name: str) -> None: ...
    def add_date_time_value(self, instance: int, name: str) -> None: ...
    def add_date_pattern_value(self, instance: int, name: str) -> None: ...
    def add_time_pattern_value(self, instance: int, name: str) -> None: ...
    def add_date_time_pattern_value(self, instance: int, name: str) -> None: ...
    def add_accumulator(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_pulse_converter(self, instance: int, name: str, units: int = 62) -> None: ...
    def add_file(self, instance: int, name: str, file_type: str = "application/octet-stream") -> None: ...
    def add_network_port(self, instance: int, name: str, network_type: int = 0) -> None: ...
    def add_event_enrollment(self, instance: int, name: str, event_type: int = 0) -> None: ...
    def add_channel(self, instance: int, name: str, channel_number: int) -> None: ...
    def add_staging(self, instance: int, name: str, num_stages: int) -> None: ...
    def add_lift(self, instance: int, name: str, num_floors: int) -> None: ...

    # Runtime methods (call after start)
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def local_address(self) -> str: ...
    async def read_property(
        self,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        array_index: Optional[int] = None,
    ) -> PropertyValue: ...
    async def write_property_local(
        self,
        object_id: ObjectIdentifier,
        property_id: PropertyIdentifier,
        value: PropertyValue,
        priority: Optional[int] = None,
        array_index: Optional[int] = None,
    ) -> None: ...
    async def comm_state(self) -> int: ...

class ScHub:
    def __init__(
        self,
        listen: str,
        cert: str,
        key: str,
        vmac: bytes,
        ca_cert: Optional[str] = None,
    ) -> None: ...

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def address(self) -> Optional[str]: ...
    async def url(self) -> Optional[str]: ...
