use super::super::*;

#[pymethods]
impl BACnetServer {
    #[new]
    #[pyo3(signature = (
        device_instance,
        device_name="BACnet Device",
        interface="0.0.0.0",
        port=0xBAC0,
        broadcast_address="255.255.255.255",
        transport="bip",
        sc_hub=None,
        sc_vmac=None,
        sc_ca_cert=None,
        sc_client_cert=None,
        sc_client_key=None,
        sc_heartbeat_interval_ms=None,
        sc_heartbeat_timeout_ms=None,
        ipv6_interface=None,
        dcc_password=None,
        reinit_password=None,
        *,
        mutation_policy="permissive",
        dcc_policy="deny_all",
        dcc_source_restriction=None,
        dcc_disable_rate_limit=None,
        serial_port=None,
        mstp_baud=38400,
        mstp_mac=1,
        mstp_max_master=127,
        mstp_max_info_frames=1,
        max_confirmed_in_flight=64,
        max_unconfirmed_in_flight=32,
        max_confirmed_in_flight_per_peer=16,
        max_unconfirmed_in_flight_per_peer=8,
        confirmed_recovery_reserve=4,
        max_recovery_in_flight_per_peer=1,
        rpm_max_result_elements=256,
        rpm_max_service_ack_bytes=16384,
        alarm_summary_max_objects=4096,
        alarm_summary_max_service_ack_bytes=16384,
        enrollment_summary_max_objects=4096,
        enrollment_summary_max_service_ack_bytes=16384,
        atomic_read_file_max_requested_stream_octets=16384,
        atomic_read_file_max_requested_records=256,
        atomic_read_file_max_service_ack_bytes=16384,
        atomic_write_file_max_stream_payload_octets=16384,
        atomic_write_file_max_records=256,
        atomic_write_file_max_record_payload_bytes=16384,
        read_range_max_returned_items=256,
        read_range_max_service_ack_bytes=16384,
        event_information_max_objects=4096,
        event_information_max_returned_summaries=256,
        event_information_max_service_ack_bytes=16384,
        sc_device_uuid=None,
        registered_network_port=None,
        cov_policy=None,
        time_sync_policy=None,
        share_port_by_address=false,
        segmentation_supported=crate::types::PySegmentation { inner: bacnet_types::enums::Segmentation::NONE },
        apdu_segment_timeout_ms=5000
    ))]
    fn new(
        device_instance: u32,
        device_name: &str,
        interface: &str,
        port: u16,
        broadcast_address: &str,
        transport: &str,
        sc_hub: Option<String>,
        sc_vmac: Option<Vec<u8>>,
        sc_ca_cert: Option<String>,
        sc_client_cert: Option<String>,
        sc_client_key: Option<String>,
        sc_heartbeat_interval_ms: Option<u64>,
        sc_heartbeat_timeout_ms: Option<u64>,
        ipv6_interface: Option<String>,
        dcc_password: Option<String>,
        reinit_password: Option<String>,
        mutation_policy: &str,
        dcc_policy: &str,
        dcc_source_restriction: Option<Vec<(Option<u16>, Vec<u8>)>>,
        dcc_disable_rate_limit: Option<(u32, u64)>,
        serial_port: Option<String>,
        mstp_baud: u32,
        mstp_mac: u8,
        mstp_max_master: u8,
        mstp_max_info_frames: u8,
        max_confirmed_in_flight: usize,
        max_unconfirmed_in_flight: usize,
        max_confirmed_in_flight_per_peer: usize,
        max_unconfirmed_in_flight_per_peer: usize,
        confirmed_recovery_reserve: usize,
        max_recovery_in_flight_per_peer: usize,
        rpm_max_result_elements: usize,
        rpm_max_service_ack_bytes: usize,
        alarm_summary_max_objects: usize,
        alarm_summary_max_service_ack_bytes: usize,
        enrollment_summary_max_objects: usize,
        enrollment_summary_max_service_ack_bytes: usize,
        atomic_read_file_max_requested_stream_octets: usize,
        atomic_read_file_max_requested_records: usize,
        atomic_read_file_max_service_ack_bytes: usize,
        atomic_write_file_max_stream_payload_octets: usize,
        atomic_write_file_max_records: usize,
        atomic_write_file_max_record_payload_bytes: usize,
        read_range_max_returned_items: usize,
        read_range_max_service_ack_bytes: usize,
        event_information_max_objects: usize,
        event_information_max_returned_summaries: usize,
        event_information_max_service_ack_bytes: usize,
        sc_device_uuid: Option<Vec<u8>>,
        registered_network_port: Option<u32>,
        cov_policy: Option<&Bound<'_, pyo3::types::PyDict>>,
        time_sync_policy: Option<&Bound<'_, pyo3::types::PyDict>>,
        share_port_by_address: bool,
        segmentation_supported: crate::types::PySegmentation,
        apdu_segment_timeout_ms: u64,
    ) -> PyResult<Self> {
        let segmentation_supported = super::constructor_budgets::segmentation(
            segmentation_supported,
            apdu_segment_timeout_ms,
        )?;
        crate::bip_options::only_on_bip(share_port_by_address, transport)?;
        super::constructor_budgets::registered_network_port(registered_network_port, transport)?;
        let mutation_policy = super::constructor_budgets::mutation_policy(mutation_policy)?;
        let super::constructor_budgets::DccConfiguration {
            policy: dcc_policy,
            source_restriction: dcc_source_restriction,
            disable_rate_limit: dcc_disable_rate_limit,
        } = super::constructor_budgets::dcc_configuration(
            dcc_policy,
            &dcc_password,
            dcc_source_restriction,
            dcc_disable_rate_limit,
        )?;
        let super::constructor_budgets::Budgets {
            request_admission_policy,
            read_property_multiple_budget,
            get_alarm_summary_budget,
            get_enrollment_summary_budget,
            atomic_read_file_budget,
            atomic_write_file_budget,
            read_range_budget,
            get_event_information_budget,
        } = super::constructor_budgets::budgets(super::constructor_budgets::BudgetKeywords {
            max_confirmed_in_flight,
            max_unconfirmed_in_flight,
            max_confirmed_in_flight_per_peer,
            max_unconfirmed_in_flight_per_peer,
            confirmed_recovery_reserve,
            max_recovery_in_flight_per_peer,
            rpm_max_result_elements,
            rpm_max_service_ack_bytes,
            alarm_summary_max_objects,
            alarm_summary_max_service_ack_bytes,
            enrollment_summary_max_objects,
            enrollment_summary_max_service_ack_bytes,
            atomic_read_file_max_requested_stream_octets,
            atomic_read_file_max_requested_records,
            atomic_read_file_max_service_ack_bytes,
            atomic_write_file_max_stream_payload_octets,
            atomic_write_file_max_records,
            atomic_write_file_max_record_payload_bytes,
            read_range_max_returned_items,
            read_range_max_service_ack_bytes,
            event_information_max_objects,
            event_information_max_returned_summaries,
            event_information_max_service_ack_bytes,
        })?;
        let cov_policy = super::cov_policy::cov_policy(cov_policy)?;
        let time_sync_policy = super::time_sync_policy::time_sync_policy(time_sync_policy)?;
        if transport == "sc" {
            crate::tls::required_sc_credentials(
                sc_ca_cert.as_deref(),
                sc_client_cert.as_deref(),
                sc_client_key.as_deref(),
            )
            .map_err(|e| pyo3::exceptions::PyValueError::new_err(e.to_string()))?;
        }
        let sc_device_uuid = crate::sc_identity::device_uuid(transport, sc_device_uuid)?;
        Ok(Self {
            inner: Arc::new(Mutex::new(None)),
            device_instance,
            segmentation_supported,
            apdu_segment_timeout_ms,
            device_name: device_name.to_string(),
            transport_type: transport.to_string(),
            interface: interface.to_string(),
            port,
            broadcast_address: broadcast_address.to_string(),
            share_port_by_address,
            registered_network_port,
            sc_hub,
            sc_vmac,
            sc_device_uuid,
            sc_ca_cert,
            sc_client_cert,
            sc_client_key,
            sc_heartbeat_interval_ms,
            sc_heartbeat_timeout_ms,
            ipv6_interface,
            serial_port,
            mstp_baud,
            mstp_mac,
            mstp_max_master,
            mstp_max_info_frames,
            dcc_password,
            mutation_policy,
            dcc_policy,
            dcc_source_restriction,
            dcc_disable_rate_limit,
            reinit_password,
            request_admission_policy,
            read_property_multiple_budget,
            get_alarm_summary_budget,
            get_enrollment_summary_budget,
            atomic_read_file_budget,
            atomic_write_file_budget,
            read_range_budget,
            get_event_information_budget,
            cov_policy,
            time_sync_policy,
            audit_notification_sink: None,
            audit_reporters: None,
            audit_recipient: std::sync::Mutex::new(None),
            device_bindings: std::collections::BTreeMap::new(),
            forwarding_configuration_started: AtomicBool::new(false),
            started: Arc::new(AtomicBool::new(false)),
            pending_objects: std::sync::Mutex::new(Vec::new()),
            pending_forwarder_save_counters: std::sync::Mutex::new(Vec::new()),
            forwarder_save_counters: Arc::new(std::sync::Mutex::new(Vec::new())),
        })
    }

    /// Test seam for verifying that fallible startup leaves registrations intact.
    #[doc(hidden)]
    fn _pending_registration_count(&self) -> PyResult<usize> {
        Ok(self.lock_pending()?.len())
    }
}
